# Generated by Django 2.2.12 on 2020-04-06 09:48

import csv_to_genie2.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numdos', models.CharField(max_length=8, validators=[csv_to_genie2.models.numdos_validator])),
                ('refdoc', models.CharField(max_length=200)),
                ('datoff', models.DateField(blank=True, null=True)),
                ('ancart', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numdos', models.CharField(max_length=8, validators=[csv_to_genie2.models.numdos_validator])),
                ('numdosvl', models.CharField(max_length=8, validators=[csv_to_genie2.models.numdos_validator])),
                ('format', models.CharField(choices=[('PDFC', 'PDFC'), ('PDFI', 'PDFI'), ('XML', 'XML')], default='PDFC', max_length=4)),
                ('verling', models.CharField(choices=[('E', 'E'), ('F', 'F'), ('F/E', 'F/E')], default='E', max_length=3)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csv_to_genie2.Standard')),
            ],
        ),
    ]
