# Generated by Django 2.2.12 on 2020-04-06 13:26

import csv_to_genie2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_to_genie2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='numdos',
            field=models.CharField(max_length=8, unique=True, validators=[csv_to_genie2.models.numdos_validator]),
        ),
    ]
